#
# IMPORTANT: DO NOT EDIT THIS FILE
#

source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '4.1.5'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0',          group: :doc

group :development, :test do
  gem 'factory_girl_rails'
  gem 'guard-rspec', require: false
  gem 'rspec-rails'
end
