# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f908a086b43fbe38b40f585826f3778ee32a29737d660ee69c795ced3ab2f75b44f4457f014b7ce00a1f10af0516759da4e5701d94dc0575e788a9ec64ef88a1

test:
  secret_key_base: fa3fe8cb7859f6a22f348abf7364ab2bee57d43fea3ed65251774776125565efea60ba3e4bea47bece6770ccfb6934ee47ab4affd4539a486e2ab2cc97c62bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
